### ISSUE TITLE
Image Compression not working on Ultra HD Images

### ISSUE THREAD

**Issue by husainali72** [eihror/ci-compress-image#1]
Hi there, 

I have uploaded a 6.7MB image and this script is unable to compress that image either not giving any error on the console to check too.

I have added this image along with this conversation.

Please check and let me know if anything else required from my side.

Best 
Husain
![for_honor_season_six_heros_march_4k_8k-7680x4320](https://user-images.githubusercontent.com/4034650/42725877-087a56f2-87a9-11e8-8d51-04b5668c5fb7.jpg)

**Comment by eihror** [comment]
Hi Husain.... I'll check this for you.

**Comment by eihror** [comment]
Hey man... I'm sorry for the delay to answer you... I finally got time to fix this.

Now its working. I used the same image that you used and now the file size error message appears.

I created a sample to helping you and anyone that want to use.
Other thing that a make its png´s quality configuration..
